# Generated by Django 5.2 on 2025-04-07 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='role',
            field=models.SmallIntegerField(choices=[(1, 'Admin'), (2, 'Manager'), (3, 'User'), (4, 'Owner')], default=3),
        ),
    ]
