# Generated by Django 5.2 on 2025-04-07 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_account_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='role',
            field=models.SmallIntegerField(choices=[(1, 'Admin'), (2, 'Owner'), (3, 'Manager'), (4, 'User')], default=4),
        ),
    ]
