# Generated by Django 5.2 on 2025-04-08 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_account_created_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='username',
        ),
    ]
