# Generated by Django 5.2 on 2025-04-09 19:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stadium', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='starting_time')),
                ('end_time', models.DateTimeField(verbose_name='end_time')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('stadium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='stadium.stadium', verbose_name='Stadium')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL, verbose_name='booking_user')),
            ],
        ),
    ]
